### ISSUE TITLE
Scale effect not working after second drag and drop in the same list

### ISSUE THREAD

**Issue by ashishguptas** [flowforfrank/drag-n-drop#1]
The scale effect is not working in drag and drop. If you drag and drop the same list

This image is scale effect...

![with-scale-effect](https://user-images.githubusercontent.com/40588377/81811471-4c609680-9542-11ea-898b-e606c0539330.jpeg)

This image is without scale effect...

![without-scale-effect](https://user-images.githubusercontent.com/40588377/81811478-4e2a5a00-9542-11ea-9ec5-8220a9b4559f.jpeg)

Thanks
:)

**Comment by flowforfrank** [comment]
This happens because when you drag the card to another column, the column's HTML is updated. Since the event listeners are attached to the card itself, these will get detached as they are inside the column. To fix this, you need to delegate the event listener instead. This way, they will be present event after the DOM is updated.
```JavaScript
document.addEventListener('dragstart', e => {
  if (e.target.className.includes('card')) {
    dragStart(e.target);
  }
});
```
Please see the **README** file and `drag-n-drop.js`. I have updated both in [#111932a](https://github.com/flowforfrank/drag-n-drop/commit/111932a01977410b1806cf2985e1785ad574afa5)
